{{-- HeadingsBlock - Generated by TallCMS --}}
{{-- TODO: Add CSS styles for '.headings-block' in resources/css/blocks.css --}}

@php
    // Get current theme presets for consistent styling
    $textPresets = \theme_text_presets();
    $textPreset = $textPresets['primary'] ?? [
        'heading' => '#111827',
        'description' => '#374151'
    ];
    
    // Build inline CSS custom properties for this block instance
    $customProperties = collect([
        '--block-heading-color: ' . $textPreset['heading'],
        '--block-text-color: ' . $textPreset['description'],
    ])->join('; ') . ';';
@endphp

<section class="headings-block py-8 px-4 max-w-4xl mx-auto" style="{{ $customProperties }}">
    @if($title)
        <h2 class="text-2xl font-bold mb-4">
            {{ $title }}
        </h2>
    @endif
    
    @if($description)
        <div class="text-lg leading-relaxed">
            {!! nl2br(e($description)) !!}
        </div>
    @endif
</section>

{{-- 
    TallCMS CSS Custom Properties Approach:
    - CSS styling defined in resources/css/blocks.css using .headings-block selector
    - Theme colors injected via CSS custom properties (--block-heading-color, etc.)
    - Perfect consistency between admin preview and frontend
    
    To customize this block:
    1. Add more form fields in the configureEditorAction method
    2. Update both toPreviewHtml and toHtml methods with new variables
    3. Add CSS styles in resources/css/blocks.css
    4. Use CSS custom properties for theme integration: color: var(--block-heading-color);
    5. Run 'npm run build' to compile assets
--}}