{{-- ParallaxBlock - Generated by TallCMS --}}
<div class="py-8 px-4 max-w-4xl mx-auto" 
     style="padding: 2rem 1rem; max-width: 56rem; margin: 0 auto;">
    @if($title)
        <h2 class="text-2xl font-bold text-gray-900 mb-4" 
            style="font-size: 1.5rem; font-weight: bold; color: #111827; margin-bottom: 1rem;">
            {{ $title }}
        </h2>
    @endif
    
    @if($description)
        <div class="text-lg text-gray-700 leading-relaxed" 
             style="font-size: 1.125rem; color: #374151; line-height: 1.75;">
            {!! nl2br(e($description)) !!}
        </div>
    @endif
</div>

{{-- 
    TallCMS Hybrid Styling Approach:
    - Tailwind classes provide primary styling and responsiveness
    - Inline styles ensure consistent rendering in admin previews
    - Both work together for maximum compatibility
    
    To customize this block:
    1. Add more form fields in the configureEditorAction method
    2. Update both toPreviewHtml and toHtml methods with new variables
    3. Modify this template to match your design requirements
    4. Follow the hybrid styling pattern (classes + inline styles)
--}}