{{-- PricingBlock - Generated by TallCMS --}}
{{-- TODO: Add CSS styles for '.pricing-block' in resources/css/blocks.css --}}

@php
    // Get current theme presets for consistent styling
    $textPresets = theme_text_presets();
    $buttonPresets = theme_button_presets();
    
    $textPreset = $textPresets['primary'] ?? [
        'heading' => '#111827',
        'description' => '#374151'
    ];
    
    $buttonPreset = $buttonPresets['primary'] ?? [
        'bg' => '#2563eb',
        'text' => '#ffffff',
        'hover' => '#1d4ed8'
    ];
    
    // Ensure all required keys exist
    $buttonPreset = array_merge([
        'bg' => '#2563eb',
        'text' => '#ffffff',
        'hover' => '#1d4ed8'
    ], $buttonPreset);
    
    // Build inline CSS custom properties for this block instance
    $customProperties = collect([
        '--block-heading-color: ' . $textPreset['heading'],
        '--block-text-color: ' . $textPreset['description'],
        '--block-button-bg: ' . $buttonPreset['bg'],
        '--block-button-text: ' . $buttonPreset['text'],
        '--block-button-hover-bg: ' . $buttonPreset['hover'],
    ])->join('; ') . ';';
    
    // Default values
    $plans = $plans ?? [];
    $section_title = $section_title ?? '';
    $section_subtitle = $section_subtitle ?? '';
    $text_alignment = $text_alignment ?? 'center';
    $columns = $columns ?? '3';
    $card_style = $card_style ?? 'shadow';
    $spacing = $spacing ?? 'normal';
    
    // Grid classes based on columns
    $gridClasses = match($columns) {
        '1' => 'grid-cols-1',
        '2' => 'grid-cols-1 md:grid-cols-2',
        '3' => 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
        '4' => 'grid-cols-1 md:grid-cols-2 lg:grid-cols-4',
        default => 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3'
    };
    
    // Text alignment classes
    $alignmentClass = match($text_alignment) {
        'left' => 'text-left',
        'center' => 'text-center',
        'right' => 'text-right',
        default => 'text-center'
    };
    
    // Spacing classes
    $gapClass = match($spacing) {
        'tight' => 'gap-4',
        'normal' => 'gap-6',
        'relaxed' => 'gap-8',
        default => 'gap-6'
    };
@endphp

<section class="pricing-block py-12 px-4" style="{{ $customProperties }}">
    <div class="max-w-7xl mx-auto">
        
        {{-- Header Section --}}
        @if($section_title || $section_subtitle)
            <div class="mb-12 {{ $alignmentClass }}">
                @if($section_title)
                    <h2 class="text-3xl md:text-4xl font-bold mb-4">
                        {{ $section_title }}
                    </h2>
                @endif
                
                @if($section_subtitle)
                    <p class="text-lg md:text-xl max-w-3xl {{ $text_alignment === 'center' ? 'mx-auto' : '' }}">
                        {{ $section_subtitle }}
                    </p>
                @endif
            </div>
        @endif
        
        {{-- Pricing Plans Grid --}}
        @if(!empty($plans))
            <div class="grid {{ $gridClasses }} {{ $gapClass }}">
                @foreach($plans as $plan)
                    @php
                        $isPopular = $plan['is_popular'] ?? false;
                        $planName = $plan['name'] ?? 'Plan';
                        $planDescription = $plan['description'] ?? '';
                        $currencySymbol = $plan['currency_symbol'] ?? '$';
                        $price = $plan['price'] ?? '0';
                        $billingPeriod = $plan['billing_period'] ?? 'month';
                        $discountText = $plan['discount_text'] ?? '';
                        $popularBadgeText = $plan['popular_badge_text'] ?? 'Most Popular';
                        $features = $plan['features'] ?? [];
                        $buttonText = $plan['button_text'] ?? 'Get Started';
                        $buttonUrl = $plan['button_url'] ?? '#';
                        $buttonStyle = $plan['button_style'] ?? 'primary';
                        $trialText = $plan['trial_text'] ?? '';
                        
                        // Card classes based on style and popularity
                        $cardClasses = [
                            'pricing-card',
                            'relative',
                            'bg-white',
                            'rounded-lg',
                            'p-6',
                            'h-full',
                            'flex',
                            'flex-col'
                        ];
                        
                        if ($card_style === 'bordered') {
                            $cardClasses[] = 'border-2';
                            $cardClasses[] = $isPopular ? 'border-primary-500' : 'border-gray-200';
                        } elseif ($card_style === 'shadow') {
                            $cardClasses[] = $isPopular ? 'shadow-xl border-2 border-primary-500' : 'shadow-lg';
                        } elseif ($card_style === 'elevated') {
                            $cardClasses[] = $isPopular ? 'shadow-2xl transform scale-105 border-2 border-primary-500' : 'shadow-lg';
                        }
                        
                        if ($isPopular) {
                            $cardClasses[] = 'bg-primary-50';
                        }
                    @endphp
                    
                    <div class="{{ implode(' ', $cardClasses) }}">
                        
                        {{-- Popular Badge --}}
                        @if($isPopular && $popularBadgeText)
                            <div class="absolute -top-3 left-1/2 transform -translate-x-1/2">
                                <span class="pricing-popular-badge bg-primary-500 text-white text-sm font-medium px-4 py-1 rounded-full">
                                    {{ $popularBadgeText }}
                                </span>
                            </div>
                        @endif
                        
                        {{-- Plan Header --}}
                        <div class="text-center mb-6">
                            <h3 class="text-xl font-bold mb-2">{{ $planName }}</h3>
                            
                            @if($planDescription)
                                <p class="text-sm text-gray-600 mb-4">{{ $planDescription }}</p>
                            @endif
                            
                            {{-- Price Display --}}
                            <div class="pricing-price-display mb-2">
                                @if($billingPeriod === 'free')
                                    <div class="text-4xl font-bold">Free</div>
                                @else
                                    <div class="flex items-baseline justify-center">
                                        <span class="text-lg">{{ $currencySymbol }}</span>
                                        <span class="text-4xl font-bold">{{ $price }}</span>
                                        @if($billingPeriod !== 'one-time')
                                            <span class="text-sm text-gray-600 ml-1">/{{ str_replace('per ', '', $billingPeriod) }}</span>
                                        @endif
                                    </div>
                                @endif
                            </div>
                            
                            @if($discountText)
                                <div class="pricing-discount text-sm text-green-600 font-medium">
                                    {{ $discountText }}
                                </div>
                            @endif
                        </div>
                        
                        {{-- Features List --}}
                        @if(!empty($features))
                            <ul class="pricing-features space-y-3 mb-8 flex-grow">
                                @foreach($features as $feature)
                                    @php
                                        $featureText = $feature['text'] ?? '';
                                        $isIncluded = $feature['included'] ?? true;
                                        $tooltip = $feature['tooltip'] ?? '';
                                    @endphp
                                    
                                    @if($featureText)
                                        <li class="flex items-start">
                                            <span class="pricing-feature-icon flex-shrink-0 w-5 h-5 mr-3 mt-0.5">
                                                @if($isIncluded)
                                                    <svg class="w-5 h-5 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                                                    </svg>
                                                @else
                                                    <svg class="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                                                    </svg>
                                                @endif
                                            </span>
                                            <span class="pricing-feature-text {{ $isIncluded ? '' : 'text-gray-500 line-through' }}">
                                                {{ $featureText }}
                                            </span>
                                        </li>
                                    @endif
                                @endforeach
                            </ul>
                        @endif
                        
                        {{-- Call to Action --}}
                        <div class="mt-auto text-center">
                            @if($buttonText)
                                @php
                                    $buttonClasses = [
                                        'pricing-button',
                                        'w-full',
                                        'py-3',
                                        'px-6',
                                        'rounded-lg',
                                        'font-medium',
                                        'transition-colors',
                                        'duration-200'
                                    ];
                                    
                                    if ($buttonStyle === 'primary') {
                                        $buttonClasses = array_merge($buttonClasses, [
                                            'bg-primary-600',
                                            'text-white',
                                            'hover:bg-primary-700'
                                        ]);
                                    } elseif ($buttonStyle === 'secondary') {
                                        $buttonClasses = array_merge($buttonClasses, [
                                            'bg-gray-600',
                                            'text-white',
                                            'hover:bg-gray-700'
                                        ]);
                                    } elseif ($buttonStyle === 'outline') {
                                        $buttonClasses = array_merge($buttonClasses, [
                                            'border-2',
                                            'border-primary-600',
                                            'text-primary-600',
                                            'hover:bg-primary-600',
                                            'hover:text-white'
                                        ]);
                                    }
                                @endphp
                                
                                <a href="{{ $buttonUrl }}" class="{{ implode(' ', $buttonClasses) }}">
                                    {{ $buttonText }}
                                </a>
                            @endif
                            
                            @if($trialText)
                                <p class="pricing-trial-text text-xs text-gray-500 mt-2">
                                    {{ $trialText }}
                                </p>
                            @endif
                        </div>
                    </div>
                @endforeach
            </div>
        @endif
        
    </div>
</section>

{{-- 
    TallCMS Comprehensive Pricing Block:
    - Complete pricing table with multiple plans and features
    - CSS styling defined in resources/css/blocks.css using .pricing-block selectors
    - Theme colors injected via CSS custom properties (--block-*, --block-button-*)
    - Perfect consistency between admin preview and frontend
    - Responsive design with configurable columns and spacing
    - Popular plan highlighting and various card styles
    - Feature lists with included/excluded states
    - Customizable call-to-action buttons with different styles
    
    Configuration includes:
    - Section header with title and subtitle
    - Multiple pricing plans with repeater fields
    - Feature lists with checkmarks/x marks
    - Popular plan badges and highlighting
    - Flexible layout options (1-4 columns)
    - Different card styles and spacing options
    - Button styling and trial text options
--}}